### ISSUE TITLE
Hard coded path to the plugin link

### ISSUE THREAD

**Issue by LucasFoulonMongai** [vpedak/droidtestrec#1]
Hello,
In this file :
com/vpedak/testsrecorder/plugin/actions/ToolsTestsRecorderAction.java

The path to the plugin file is hard coded, so it can't work on any other computer than yours.

Error description :
<code>
Error:Cannot convert URL 'C:/Users/vpedak/IdeaProjects/droidtestrec/AndroidTestsRecorder.jar' to a file.
</code>

**Comment by LucasFoulonMongai** [comment]
@vpedak up :)

**Comment by wrparrish** [comment]
Do you  know when we can expect this change to be present in the plugin on Android Studio?
I downloaded it today, and saw the same problem.

Thank you!  Very excited to use it.

**Comment by vpedak** [comment]
Sorry, I was sure that problem is only in sources and binary version of
plugin itself does not has this problem. I will upload new plugin later
today.

Thanks,
Slava Pedak

**Comment by wrparrish** [comment]
Awesome!   Looking forward to it.

**Comment by vpedak** [comment]
I've uploaded new version to the repository, but it will take some time when it will be available (1-2 days) but you can download it also directly from site - http://droidtestlab.com/AndroidTestsRecorder.zip
And install into your Android Studio from file (not from repository). Please let me know if the problem is resolved at your side.
