### ISSUE TITLE
button to clear logs

### ISSUE THREAD

**Issue by fahimk** [vpedak/droidtestrec#13]
would be nice to have a way of clearing the logs without stop/start which rebuilds the module

**Comment by vpedak** [comment]
Why do we need to have a button to clear the log? What is the use case when somebody will want to clear the log? It user want to record something new, log will be cleared automatically. I do not think that such functionality.

**Comment by fahimk** [comment]
@vpedak I don't think the test recorder can be used entirely for generating tests, the code needs to be manually modified for anything more than a simple app. In this case it would be nice to have the app open and not have to rebuild/restart to add record a few actions at a time

**Comment by vpedak** [comment]
ok, I see your point, but you can not simple add few actions because you are starting application each time recording is started (there is no choice), so you will have to go through application one more time to go to the point where you were. 
What you can do now, you can start new recording, go through the application and not generate a test, but simple select subset of generated events, right click and generate code to clipboard (there is a menu for this) and then paste generated events to your test. So you will have ability to add some new events to already created test.
